/* This is file is automatically generated */
#define BUILD_ARCH "linuxx8664gcc"
#define BUILD_NODE "Linux gluon100.jlab.org 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux"
#define CXX "c++"
#define COMPILER "/apps/gcc/4.9.2/bin/c++"
#define COMPILERVERS "c++"
#define MAKESHAREDLIB  "cd $BuildDir ; c++ -c $Opt -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread -Wno-deprecated-declarations $IncludePath $SourceFiles ; c++ $ObjectFiles -shared  $LinkedLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; c++ -c  -pipe -m64 -W -Woverloaded-virtual -fPIC -pthread -Wno-deprecated-declarations $IncludePath $SourceFiles; c++ $ObjectFiles  -o $ExeName $LinkedLibs -lm -ldl -lpthread -rdynamic"
#define CXXOPT "-O2 -DNDEBUG"
#define CXXDEBUG "-g  -fno-reorder-blocks -fno-schedule-insns -fno-inline"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o"
#define SOEXT "so"
